name = "Hugo Baesd Bloxxx"
license = "MIT"
licenselink = "https://github.com/jkrebian/jkrebian.github.io/blob/main/LICENSE"
description = "Hugo Based Bloxxx"

homepage = "https://github.com/jkrebian/jkrebian.github.io"
deploysite = "https://jkrebian.netlify.app"

tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "John Krebian"
  homepage = "https://jkrebian.github.io/"
